plugins {
    id 'java'
    id 'application'
}

group 'org.bold'
version '0.2.0'

//sourceCompatibility = 1.8
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    testImplementation group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.10'

    implementation group: 'org.eclipse.rdf4j', name : 'rdf4j-storage', version: '3.2.0'
    implementation group: 'org.eclipse.jetty', name: 'jetty-server', version: '9.4.28.v20200408'
    implementation group: 'org.eclipse.jetty', name: 'jetty-servlet', version: '9.4.28.v20200408'
    implementation group: 'org.glassfish.jersey.containers', name: 'jersey-container-servlet', version: '2.41'
    implementation group: 'org.glassfish.jersey.inject', name: 'jersey-hk2', version: '2.41'

    implementation group: 'org.antlr', name: 'antlr4', version: '4.12.0'
    implementation group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.30'

    implementation files('libs/ldp-sail-0.1.0.jar')
}

application {
    mainClass = 'org.bold.Configurator'
}

distributions {
    main {
        contents {
            // copies relevant configuration files to dist folder
            from('data') { into('data') }
            from('query') { into('query') }
            from('doc') { into('doc') }
            from('.') { include('*.properties') }
            from('libs') { into('libs') }
        }
    }
}

tasks.register('runBold', JavaExec) {
    group = 'application'
    description = 'Run the application.'
    classpath = sourceSets.main.runtimeClasspath
    mainClass.set(application.mainClass)
    environment 'BOLD_SERVER_BASE_URI', 'http://127.0.1.1:8080/'
    dependsOn 'installDist'
}