PREFIX dyn:  <https://paul.ti.rw.fau.de/~am52etar/dynmaze/dynmaze#>
PREFIX maze: <https://kaefer3000.github.io/2021-02-dagstuhl/vocab#>

DELETE {
    # Target Graph: Cleanup Request. TODO: potential for stigmergy
    GRAPH <http://127.0.1.1:8080/cells/0> {
        ?agent dyn:entersFrom <http://127.0.1.1:8080/maze> .
    }
}
INSERT {
    # Target Graph: Containment statement
    GRAPH <http://127.0.1.1:8080/cells/0> {
        <http://127.0.1.1:8080/cells/0> maze:contains ?agent .
    }
    # Origin Graph: success statement
    GRAPH <http://127.0.1.1:8080/maze> {
        ?agent dyn:moveSucceeded <http://127.0.1.1:8080/cells/0> .
    }
}
WHERE {
    # the move event to the first cell
    GRAPH <http://127.0.1.1:8080/cells/0> {
        ?agent dyn:entersFrom <http://127.0.1.1:8080/maze> .
    }
}
