# Rule to toggle switch in Hall of Knives (cell 1)
# Changes east connection from cell 6 to cell 22 and adds green connection
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX maze: <https://kaefer3000.github.io/2021-02-dagstuhl/vocab#>

CONSTRUCT {
    <http://127.0.1.1:8080/cells/1> maze:east <http://127.0.1.1:8080/cells/22> .
    <http://127.0.1.1:8080/cells/1> maze:green <http://127.0.1.1:8080/cells/22> .
}
WHERE {
    GRAPH <http://127.0.1.1:8080/cells/1> {
        <http://127.0.1.1:8080/cells/1> rdf:type maze:Cell ;
            rdfs:label "Hall of Knives" ;
            maze:east <http://127.0.1.1:8080/cells/6> .
    }
}
