# Rule to toggle switch in Hobby Room (cell 16)
# Changes green/east connection from cell 21 to cell 1
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX maze: <https://kaefer3000.github.io/2021-02-dagstuhl/vocab#>

CONSTRUCT {
    <http://127.0.1.1:8080/cells/16> maze:green <http://127.0.1.1:8080/cells/1> .
    <http://127.0.1.1:8080/cells/16> maze:east <http://127.0.1.1:8080/cells/1> .
}
WHERE {
    GRAPH <http://127.0.1.1:8080/cells/16> {
        <http://127.0.1.1:8080/cells/16> a maze:Cell ;
            rdfs:label "Hobby Room" ;
            maze:green <http://127.0.1.1:8080/cells/21> ;
            maze:east <http://127.0.1.1:8080/cells/21> .
    }
}
