# CCRS scenario package
mase.scenario.id = ccrs
mase.scenario.name = CCRS Maze
mase.init.dataset = data/CcrsMazeV1.trig
mase.rules.path = rules/**/*.rq
mase.transaction.trace = summary
mase.rules.execution.order= normalize_maze_locks*, ccrs*, unlock*, cleanup*, move*
