# ---------------
# KEY UI-ELEMENTS
# ---------------

PREFIX dyn:  <https://paul.ti.rw.fau.de/~am52etar/dynmaze/dynmaze#>
PREFIX maze: <https://kaefer3000.github.io/2021-02-dagstuhl/vocab#>
PREFIX ui:   <https://example.org/ui#>

# Mark the location of the keys
INSERT {
    GRAPH ?g {
        ?cell ui:hasUiElement ?uiKey .

        ?uiKey ui:konvaType "Circle";
            ui:layer "layer";
            ui:anchor "SE";
            ui:offsetX 0;
            ui:offsetY 0;
            ui:width 12;
            ui:height 12;
            ui:radius 6;
            ui:fill ?fill;
            ui:stroke "black";
            ui:strokeWidth 1 .
  }
}
WHERE {
    VALUES (?key ?suffix ?fill) {
        ("greenkey" "#ui-greenkey" "green")
        ("redkey"   "#ui-redkey"   "red")
    }

    GRAPH ?g {
        ?cell a maze:Cell .

        {
            ?cell dyn:keyValue ?key .
        }
        UNION
        {
            ?keyNode dyn:keyValue ?key .
        }
    }

    BIND(IRI(CONCAT(STR(?cell), ?suffix)) AS ?uiKey)
} ;

# Cleanup key UI elements when keys are no longer present
DELETE {
    GRAPH ?g {
        ?cell ui:hasUiElement ?uiKey .
        ?uiKey ?p ?o .
    }
}
WHERE {
    VALUES (?key ?suffix) {
        ("greenkey" "#ui-greenkey")
        ("redkey"   "#ui-redkey")
    }

    GRAPH ?g {
        ?cell a maze:Cell .
    }

    BIND(IRI(CONCAT(STR(?cell), ?suffix)) AS ?uiKey)

    GRAPH ?g {
        ?uiKey ?p ?o .
    }

    FILTER NOT EXISTS {
        GRAPH ?g {
            {
                ?cell dyn:keyValue ?key .
            }
            UNION
            {
                ?keyNode dyn:keyValue ?key .
            }
        }
    }
}
