# Configuration of the simulation engine

# initialization
bold.init.dataset = data/maze-UnsafeMaze.trig

# Server configuration
bold.server.protocol = ldp

# Rule execution order
bold.rules.execution.order= unlock*, stigmergy-traffic-increment*, stigmergy-traffic-add*, stigmergy-traffic-new*, move*

