PREFIX maze: <https://kaefer3000.github.io/2021-02-dagstuhl/vocab#>
PREFIX dyn: <https://paul.ti.rw.fau.de/~am52etar/dynmaze/dynmaze#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX hydra: <http://www.w3.org/ns/hydra/core#>
PREFIX sh: <http://www.w3.org/ns/shacl#>

# --------------------
# RESET AFTER ONE MOVE
# --------------------

# Reset the cell if one agent has moved through the door -> Single passage & re-lock policy
DELETE {
  GRAPH ?g {

    # remove old state of this lock
    ?cell dyn:state ?oldState .

    # remove any old status & timestamp on this action
    ?blueAction dyn:hasStatus ?oldStatus .
    ?blueAction xsd:dateTime ?oldTimestamp .

    # remove the door to the south
    ?cell maze:south <http://127.0.1.1:8080/cells/45/45> .

    # remove the key
    ?cell dyn:keyValue ?anyKeyValue .
  }
}
INSERT {
  GRAPH ?g {
    # locked state for the cell
    ?cell dyn:state dyn:locked .

    # mark the action as open
    ?blueAction dyn:hasStatus dyn:open .
  }
}
WHERE {
  GRAPH ?g {
    ?cell a maze:Cell , dyn:Lock ;
          hydra:operation ?blueAction ;
          maze:south <http://127.0.1.1:8080/cells/45/45> .

    ?blueAction xsd:dateTime ?unlockTimestamp .

    OPTIONAL { ?cell dyn:state ?oldState . }
    OPTIONAL { ?cell dyn:keyValue ?anyKeyValue . }
    OPTIONAL { ?blueAction dyn:hasStatus ?oldStatus . }
    OPTIONAL { ?blueAction xsd:dateTime ?oldTimestamp . }

    ?moveEvent a dyn:moveSuccessEvent ;
              dyn:targetCell ?targetCell ;
              xsd:dateTime ?moveTimestamp .
  
  # Only apply if a Move occured AFTER the cell was unlocked
  FILTER(?moveTimestamp > ?unlockTimestamp)
  FILTER(?targetCell = <http://127.0.1.1:8080/cells/45/45>)

  }
} ;


# ------------------
# UNLOCK CELL IF KEY
# ------------------

# Unlock cell with blue key /45/44 - leads to cell 45/45
DELETE {
  GRAPH ?g {
    # remove old state of this lock
    ?cell dyn:state ?oldState .

    # remove any old status & timestamp on this action
    ?blueAction dyn:hasStatus ?oldStatus .
    ?blueAction xsd:dateTime ?oldTimestamp .
  }
}
INSERT {
  GRAPH ?g {
    # ensure the door to the south is present
    ?cell maze:south <http://127.0.1.1:8080/cells/45/45> .

    # new state for the cell
    ?cell dyn:state dyn:unlocked .

    # mark the action as done
    ?blueAction dyn:hasStatus dyn:done ;
                xsd:dateTime ?timestamp .
  }
}
WHERE {
  GRAPH ?g {
    ?cell a maze:Cell , dyn:Lock ;
          dyn:keyValue "bluekey-9347" ;
          hydra:operation ?blueAction .

    ?blueAction dyn:hasStatus dyn:open .

    OPTIONAL { ?cell dyn:state ?oldState . }
    OPTIONAL { ?blueAction dyn:hasStatus ?oldStatus . }
    OPTIONAL { ?blueAction xsd:dateTime ?oldTimestamp . }

    BIND( NOW() AS ?timestamp )

    FILTER(?cell = <http://127.0.1.1:8080/cells/44/45>)
  }
}
