PREFIX maze: <https://kaefer3000.github.io/2021-02-dagstuhl/vocab#>
PREFIX dyn: <https://paul.ti.rw.fau.de/~am52etar/dynmaze/dynmaze#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX hydra: <http://www.w3.org/ns/hydra/core#>

# --------------------
# RESET AFTER ONE MOVE
# --------------------

# Reset the lock after one agent has moved through the door.
DELETE {
  GRAPH ?g {
    ?cell dyn:state ?oldState .
    ?action dyn:hasStatus ?oldStatus .
    ?action xsd:dateTime ?oldTimestamp .
    ?cell ?direction ?targetCell .
    ?cell maze:green ?targetCell .
    ?cell dyn:keyValue ?anyKeyValue .
  }
}
INSERT {
  GRAPH ?g {
    ?cell dyn:state dyn:locked .
    ?action dyn:hasStatus dyn:open .
  }
}
WHERE {
  VALUES (?cell ?targetCell ?direction ?keyValue) {
    (<http://127.0.1.1:8080/cells/36/36> <http://127.0.1.1:8080/cells/36/37> maze:east  "redkey-1670")
    (<http://127.0.1.1:8080/cells/44/45> <http://127.0.1.1:8080/cells/45/45> maze:south "bluekey-9347")
    (<http://127.0.1.1:8080/cells/12/5>  <http://127.0.1.1:8080/cells/13/5>  maze:south "greenkey-4852")
  }

  GRAPH ?g {
    ?cell a maze:Cell , dyn:Lock ;
          hydra:operation ?action ;
          ?direction ?targetCell .

    ?action xsd:dateTime ?unlockTimestamp .

    OPTIONAL { ?cell dyn:state ?oldState . }
    OPTIONAL { ?cell dyn:keyValue ?anyKeyValue . }
    OPTIONAL { ?action dyn:hasStatus ?oldStatus . }
    OPTIONAL { ?action xsd:dateTime ?oldTimestamp . }

    ?moveEvent a dyn:moveSuccessEvent ;
               dyn:targetCell ?targetCell ;
               xsd:dateTime ?moveTimestamp .

    FILTER(?moveTimestamp > ?unlockTimestamp)
  }
} ;

# ------------------
# UNLOCK CELL IF KEY
# ------------------

DELETE {
  GRAPH ?g {
    ?cell dyn:state ?oldState .
    ?action dyn:hasStatus ?oldStatus .
    ?action xsd:dateTime ?oldTimestamp .
  }
}
INSERT {
  GRAPH ?g {
    ?cell ?direction ?targetCell .
    ?cell maze:green ?targetCell .
    ?cell dyn:state dyn:unlocked .
    ?action dyn:hasStatus dyn:done ;
            xsd:dateTime ?timestamp .
  }
}
WHERE {
  VALUES (?cell ?targetCell ?direction ?keyValue) {
    (<http://127.0.1.1:8080/cells/36/36> <http://127.0.1.1:8080/cells/36/37> maze:east  "redkey-1670")
    (<http://127.0.1.1:8080/cells/44/45> <http://127.0.1.1:8080/cells/45/45> maze:south "bluekey-9347")
    (<http://127.0.1.1:8080/cells/12/5>  <http://127.0.1.1:8080/cells/13/5>  maze:south "greenkey-4852")
  }

  GRAPH ?g {
    ?cell a maze:Cell , dyn:Lock ;
          dyn:keyValue ?keyValue ;
          hydra:operation ?action .

    ?action dyn:hasStatus dyn:open .

    OPTIONAL { ?cell dyn:state ?oldState . }
    OPTIONAL { ?action dyn:hasStatus ?oldStatus . }
    OPTIONAL { ?action xsd:dateTime ?oldTimestamp . }

    BIND(NOW() AS ?timestamp)
  }
}
