# MaseCreator scenario package
mase.scenario.id = masecreator
mase.scenario.name = MaseCreator
mase.init.dataset = data/MaseCreator.trig
mase.rules.path = rules/**/*.rq
mase.transaction.trace = summary
mase.rules.execution.order= unlock*, stigmergy-traffic-increment*, stigmergy-traffic-add*, stigmergy-traffic-new*, move*
