# Rule to unlock doors when orange key is found
PREFIX http: <http://www.w3.org/2011/http#>
PREFIX dyn: <https://paul.ti.rw.fau.de/~am52etar/dynmaze/dynmaze#>
PREFIX maze: <https://kaefer3000.github.io/2021-02-dagstuhl/vocab#>

CONSTRUCT {
    ?cell maze:east <http://127.0.1.1:8080/cells/50/60> .
    ?cell maze:green <http://127.0.1.1:8080/cells/50/60> .
    ?cell dyn:state dyn:unlocked .
    ?orangeAction dyn:hasStatus dyn:done .
}
WHERE {
    GRAPH ?g {
        ?cell a maze:Cell , dyn:Lock ;
              dyn:keyValue "orangekey" ;
              dyn:needsAction ?orangeAction .
        
        ?orangeAction dyn:hasStatus dyn:open ;
                      http:body ?body .
        
        ?body dyn:foundAt dyn:OrangeKey .
    }
}
