# Configuration of the simulation engine

# initialization
mase.init.dataset = data/CcrsMazeV1.trig

# Server configuration
mase.server.protocol = ldp
# To enable transaction debug traces set to true
mase.transaction.trace = false

# Rule execution order
mase.rules.execution.order= normalize_maze_locks*, ccrs*, unlock*, move*

