# Configuration of the simulation engine

# initialization
mase.init.dataset = data/SmallMaze.trig

# Server configuration
mase.server.protocol = ldp

# Rule execution order
mase.rules.execution.order= unlock*, stigmergy-traffic-increment*, stigmergy-traffic-add*, stigmergy-traffic-new*, move*

