# SmallMaze scenario package
mase.scenario.id = smallmaze
mase.scenario.name = SmallMaze
mase.init.dataset = data/SmallMaze.trig
mase.rules.path = rules/**/*.rq
mase.transaction.trace = summary
mase.rules.execution.order= unlock*, stigmergy-traffic-increment*, stigmergy-traffic-add*, stigmergy-traffic-new*, move*
