PREFIX sm: <https://example.org/stigmark#>
PREFIX dyn: <https://paul.ti.rw.fau.de/~am52etar/dynmaze/dynmaze#>
PREFIX maze: <https://kaefer3000.github.io/2021-02-dagstuhl/vocab#>

DELETE {
    # Remove old quantitative count
    GRAPH ?oldGraph {
        ?subnode sm:quantitative ?count .
    }
}
INSERT {
    # Update existing marker subnode with incremented count
    GRAPH ?oldGraph {
        ?subnode sm:quantitative ?newCount .
    }
}
WHERE {
    # the move event
    GRAPH ?targetGraph {
        ?agent dyn:entersFrom ?oldGraph .
    }

    # find the cell the agent is currently in
    GRAPH ?oldGraph {
        ?oldGraph maze:contains ?agent .

        # ensure marker does already exist
        ?oldGraph sm:hasMarker ?marker .
        
        # find existing subnode for this target
        ?marker sm:contains ?subnode .
        ?subnode sm:refersTo ?targetGraph .
        ?subnode sm:quantitative ?count .
    }

    BIND(?count + 1 AS ?newCount)
}