PREFIX sm: <https://example.org/stigmark#>
PREFIX dyn: <https://paul.ti.rw.fau.de/~am52etar/dynmaze/dynmaze#>
PREFIX maze: <https://kaefer3000.github.io/2021-02-dagstuhl/vocab#>


CONSTRUCT {
    ?cell a maze:Cell . # Provides context for merging triples in the same graph
    ?marker sm:contains _:newSub .
    _:newSub sm:refersTo ?target .
    _:newSub sm:quantitative 1 .
}
WHERE {
    GRAPH ?g {
        ?cell maze:outgoingAgent ?agent .
        ?agent maze:targetCell ?target .

        # marker exists
        ?cell sm:hasMarker ?marker .

        # ensure NO subnode for this target exists
        FILTER NOT EXISTS {
            ?marker sm:contains ?existing .
            ?existing sm:refersTo ?target .
        }
    }
}
