# Rule to unlock doors when green key is found
PREFIX http: <http://www.w3.org/2011/http#>
PREFIX dyn: <https://paul.ti.rw.fau.de/~am52etar/dynmaze/dynmaze#>
PREFIX maze: <https://kaefer3000.github.io/2021-02-dagstuhl/vocab#>

DELETE {
  GRAPH ?g {
    # remove old state of this lock
    ?cell dyn:state ?oldState .

    # remove any old status on this action
    ?greenAction dyn:hasStatus ?oldStatus .
  }
}
INSERT {
  GRAPH ?g {
    # ensure the door to the south is present
    ?cell maze:south <http://127.0.1.1:8080/cells/4/3> .
    ?cell maze:green <http://127.0.1.1:8080/cells/4/3> .

    # new state for the cell
    ?cell dyn:state dyn:unlocked .

    # mark the action as done
    ?greenAction dyn:hasStatus dyn:done .
  }
}
WHERE {
  GRAPH ?g {
    ?cell a maze:Cell , dyn:Lock ;
          dyn:keyValue "greenkey" ;
          dyn:needsAction ?greenAction .

    ?greenAction dyn:hasStatus dyn:open ;
               http:body ?body .

    ?body dyn:foundAt dyn:GreenKey .

    OPTIONAL { ?cell dyn:state ?oldState . }
    OPTIONAL { ?greenAction dyn:hasStatus ?oldStatus . }
  }
}
